name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-12
    timeout-minutes: 10 # If a build exceeds 10 mins, it probably isn't ever going to complete
    steps:
      - uses: actions/checkout@v2
      - name: MacOS Version
        run: sw_vers
      - name: Toolchain version
        run: swift -version
      - name: Build
        run: swift build
